.TH "AIThreshold" 1 "19 Mar 2020" 0.20200319 " User Manual"

.SH NAME
aithreshold

.SH SYNOPSIS
aithreshold <image_in> <image_out> [T=0.15] [part=8] [blur=0]

.SH DESCRIPTION
Adaptive Thresholding Using the Integral Image

.SH EXAMPLE
aithreshold image.png output.png 0.1 16 1

.SH COPYRIGHT
Copyright 2017-2020 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 convert(1),
 imgtxtenh(1),
 imthreshold(1)

.SH CONTACTS
 Homepage: https://github.com/zvezdochiot/aithreshold
 Email: zvezdochiot@users.sourceforge.net
